#include <string.h>
#include "bolun/hal.h"

static const BolunBoardProfile profiles[] = {
    {"Lumia 520", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 512, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;legacy_gpu;wvga_panel"},
    {"Lumia 525", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 1024, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "legacy_gpu;wvga_panel"},
    {"Lumia 530", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_200, 512, 480, 854, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;fwvga_panel"},
    {"Lumia 535", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_200, 1024, 540, 960, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "qhd_panel"},
    {"Lumia 620", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 512, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;nfc_optional"},
    {"Lumia 625", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 512, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;lte_cat3"},
    {"Lumia 630", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 512, 480, 854, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "no_flash;fwvga_panel"},
    {"Lumia 635", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 512, 480, 854, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;lte_cat4"},
    {"Lumia 640", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE, "hd_panel"},
    {"Lumia 640 XL", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE, "large_hd_panel"},
    {"Lumia 720", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 512, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE, "low_ram;clearblack"},
    {"Lumia 730", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_REMOVABLE_STORAGE, "dual_sim;oled_panel"},
    {"Lumia 735", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE, "oled_panel"},
    {"Lumia 820", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 1024, 480, 800, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE | BOLUN_FEATURE_WIRELESS_CHARGING, "amoled;replaceable_shell"},
    {"Lumia 830", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_400, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE | BOLUN_FEATURE_HIGH_RES_CAMERA, "pureview_camera"},
    {"Lumia 920", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 1024, 768, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_WIRELESS_CHARGING | BOLUN_FEATURE_HIGH_RES_CAMERA, "puremotion_hd;wireless_charging"},
    {"Lumia 925", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 1024, 768, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_HIGH_RES_CAMERA, "amoled;metal_frame"},
    {"Lumia 930", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_800, 2048, 1080, 1920, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_WIRELESS_CHARGING | BOLUN_FEATURE_HIGH_RES_CAMERA, "high_dpi;quad_mic"},
    {"Lumia 1020", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 2048, 768, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_HIGH_RES_CAMERA, "41mp_sensor;camera_grip_optional"},
    {"Lumia 1320", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_S4, 1024, 720, 1280, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_REMOVABLE_STORAGE, "large_hd_panel"},
    {"Lumia 1520", BOLUN_ARCH_ARMV7, BOLUN_SOC_SNAPDRAGON_800, 2048, 1080, 1920, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_REMOVABLE_STORAGE | BOLUN_FEATURE_HIGH_RES_CAMERA, "phablet;quad_mic"},
    {"Lumia 950", BOLUN_ARCH_ARM64, BOLUN_SOC_SNAPDRAGON_808, 3072, 1440, 2560, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_GLANCE | BOLUN_FEATURE_REMOVABLE_STORAGE | BOLUN_FEATURE_HIGH_RES_CAMERA, "usb_c;iris;continuum"},
    {"Lumia 950 XL", BOLUN_ARCH_ARM64, BOLUN_SOC_SNAPDRAGON_810, 3072, 1440, 2560, BOLUN_FEATURE_TOUCH | BOLUN_FEATURE_CAMERA | BOLUN_FEATURE_FRONT_CAMERA | BOLUN_FEATURE_LTE | BOLUN_FEATURE_NFC | BOLUN_FEATURE_GLANCE | BOLUN_FEATURE_REMOVABLE_STORAGE | BOLUN_FEATURE_HIGH_RES_CAMERA, "thermal_big_little;usb_c;iris;continuum"}
};

size_t bolun_hal_profile_count(void) { return sizeof(profiles) / sizeof(profiles[0]); }

const BolunBoardProfile *bolun_hal_profile_at(size_t index) {
    return index < bolun_hal_profile_count() ? &profiles[index] : 0;
}

const BolunBoardProfile *bolun_hal_find_profile(const char *model) {
    if (!model) return 0;
    for (size_t i = 0; i < bolun_hal_profile_count(); ++i) {
        if (strcmp(profiles[i].model, model) == 0) return &profiles[i];
    }
    return 0;
}

BolunStatus bolun_hal_validate_profile(const BolunBoardProfile *profile) {
    if (!profile || !profile->model || !profile->quirks) return BOLUN_ERROR_INVALID_ARGUMENT;
    if (profile->ram_mb < 512 || profile->display_width < 480 || profile->display_height < 800) return BOLUN_ERROR_INTEGRITY;
    if ((profile->feature_flags & BOLUN_FEATURE_TOUCH) == 0) return BOLUN_ERROR_INTEGRITY;
    return BOLUN_OK;
}

const char *bolun_hal_arch_name(BolunArch arch) {
    switch (arch) {
        case BOLUN_ARCH_ARMV7: return "ARMv7";
        case BOLUN_ARCH_ARMV8: return "ARMv8";
        case BOLUN_ARCH_ARM64: return "ARM64";
        default: return "unknown";
    }
}

const char *bolun_hal_soc_name(BolunSoc soc) {
    switch (soc) {
        case BOLUN_SOC_SNAPDRAGON_S4: return "Qualcomm Snapdragon S4";
        case BOLUN_SOC_SNAPDRAGON_200: return "Qualcomm Snapdragon 200";
        case BOLUN_SOC_SNAPDRAGON_400: return "Qualcomm Snapdragon 400";
        case BOLUN_SOC_SNAPDRAGON_800: return "Qualcomm Snapdragon 800";
        case BOLUN_SOC_SNAPDRAGON_808: return "Qualcomm Snapdragon 808";
        case BOLUN_SOC_SNAPDRAGON_810: return "Qualcomm Snapdragon 810";
        default: return "unknown";
    }
}
